name: Daily Data Refresh

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write  # Required for pushing changes

jobs:
  refresh-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install and configure uv
        run: |
          pip install uv
          uv venv
          source .venv/bin/activate
          uv pip sync pyproject.toml

      - name: Run data refresh script
        run: |
          echo "Starting data refresh..."
          uv run refresh_data.py
          echo "Data refresh completed"

      - name: Check for changes
        run: |
          echo "Files in data_parquet/:"
          ls -la data_parquet/ || echo "data_parquet/ directory not found"
          echo "Git status:"
          git status

      - name: Commit and push if data changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data_parquet/
          # Check if there are changes to commit
          if ! git diff --staged --quiet; then
            git commit -m "Automated daily data refresh - $(date -u)"
            git push origin main
          else
            echo "No data changes to commit."
          fi